# Generated from Formula/jevcode.rb in https://github.com/coasty-ai/JevCode; edit it there.
class Jevcode < Formula
  desc "Terminal coding agent that edits your code and verifies it with your tests"
  homepage "https://github.com/coasty-ai/JevCode"
  url "https://registry.npmjs.org/@coasty/jevcode/-/jevcode-0.8.0.tgz"
  sha256 "cb913d33b64ad48625fa31ee9a22ad822ae4d8f56f6d4bfbf36b9a8c25125af4"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")

    # Man page and static completions ship in the tarball (generated by scripts/gen-docs.mjs).
    pkg = libexec/"lib/node_modules/@coasty/jevcode"
    man1.install pkg/"man/jevcode.1"
    bash_completion.install pkg/"completions/jevcode.bash" => "jevcode"
    zsh_completion.install pkg/"completions/jevcode.zsh" => "_jevcode"
    fish_completion.install pkg/"completions/jevcode.fish"
  end

  test do
    assert_match "jevcode #{version}", shell_output("#{bin}/jevcode --version")
    assert_match "jevcode", shell_output("#{bin}/jevcode --help")
    assert_path_exists man1/"jevcode.1"
    assert_path_exists bash_completion/"jevcode"
    assert_path_exists zsh_completion/"_jevcode"
    assert_path_exists fish_completion/"jevcode.fish"
  end
end
